/**
 * Contract test protecting the resolution of `@agent-hangar/core` from source under bundlers that
 * do not implement Node's NodeNext extension-substitution rule.
 *
 * Layer: integration (reads the workspace tsconfig and every source file; no I/O beyond the file
 * system).
 * Goal: `tsc`, tsx and Vite/Vitest all accept a relative specifier such as `'./foo.js'` that
 * actually points at `foo.ts`, quietly rewriting or substituting the extension. Turbopack (the
 * `next dev` default bundler) does not: it resolves specifiers literally, so a `.js` specifier with
 * no matching `.js` file on disk fails with "Module not found", and because
 * `packages/core/src/index.ts` re-exports every folder barrel, that failure took down the whole
 * package the moment a web page imported from it. The fix is `rewriteRelativeImportExtensions`
 * (stable since TypeScript 5.7): every hand-written relative specifier under `src` names the real
 * `.ts` file directly, and `tsc` rewrites it to `.js` in the emitted `dist` output, so Node's ESM
 * loader still sees a valid extension in production. Both properties are asserted directly, not
 * inferred from a passing build, since a reverted flag or a reintroduced `.js` specifier would
 * still typecheck and build — only Turbopack's dev resolution would break, and that failure mode
 * is exactly what this test exists to catch ahead of `pnpm dev`.
 * Mocks: none.
 */
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
const coreSrcDir = join(repoRoot, 'packages', 'core', 'src');

/** Directories whose contents are generated (Prisma client) and out of this contract's scope. */
const EXCLUDED_DIR_SEGMENTS = [join('persistence', 'generated')];

/**
 * Recursively lists every `.ts`/`.tsx` file under a directory, skipping the excluded segments.
 *
 * @param dir - Directory to walk.
 * @returns Absolute paths of the matching files.
 */
function listSourceFiles(dir: string): string[] {
  const entries = readdirSync(dir);
  const files: string[] = [];
  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const relativePath = relative(coreSrcDir, fullPath);
    if (EXCLUDED_DIR_SEGMENTS.some((segment) => relativePath.startsWith(segment))) {
      continue;
    }
    const stats = statSync(fullPath);
    if (stats.isDirectory()) {
      files.push(...listSourceFiles(fullPath));
    } else if (entry.endsWith('.ts') || entry.endsWith('.tsx')) {
      files.push(fullPath);
    }
  }
  return files;
}

/**
 * Matches every syntactic form that can carry a relative specifier: an `import`/`export … from`
 * clause, a dynamic `import()` call, and a side-effect `import './x'` with no binding. The last
 * form has no `from`, so a pattern anchored on that keyword alone would let it through — and it
 * resolves exactly like the others, so a `.js` extension there breaks the build just the same.
 */
const RELATIVE_SPECIFIER_PATTERN =
  /(?:\bfrom\s+|\bimport\s*\(\s*|\bimport\s+(?=['"]))['"](\.\.?\/[^'"]+)['"]/g;

describe('relative specifiers of @agent-hangar/core resolve without extension substitution', () => {
  /**
   * `rewriteRelativeImportExtensions` is what lets the source tree use `.ts` specifiers while
   * `tsc` still emits Node-ESM-valid `.js` specifiers in `dist`; without it, switching the
   * specifiers below to `.ts` would break the compiled output instead of fixing dev resolution.
   */
  it('enables rewriteRelativeImportExtensions in the shared tsconfig', () => {
    const base = JSON.parse(readFileSync(join(repoRoot, 'tsconfig.base.json'), 'utf8')) as {
      compilerOptions?: Record<string, unknown>;
    };
    expect(base.compilerOptions?.rewriteRelativeImportExtensions).toBe(true);
  });

  /**
   * Every hand-written relative specifier under `src` (the generated Prisma client is exempt: it
   * is regenerated by `prisma generate`, not authored here) must name the real file on disk —
   * `.ts`/`.tsx`, never a `.js` extension that only exists after a build. A single leftover `.js`
   * specifier is enough to break Turbopack resolution of the whole barrel again, so every source
   * file is scanned, not just `index.ts`.
   */
  it('never points a relative specifier at a .js file that does not exist', () => {
    // Files whose text deliberately feeds `.js`-suffixed samples to a pattern under test, rather
    // than writing them as real import specifiers. Scanning them would report their own test data
    // as offences.
    const filesWithDeliberateJsSamples = [
      fileURLToPath(import.meta.url),
      join(coreSrcDir, 'config', 'declaration-specifiers.test.ts'),
    ];
    const offenders: string[] = [];
    for (const file of listSourceFiles(coreSrcDir)) {
      if (filesWithDeliberateJsSamples.includes(file)) {
        continue;
      }
      const content = readFileSync(file, 'utf8');
      for (const match of content.matchAll(RELATIVE_SPECIFIER_PATTERN)) {
        const specifier = match[1] ?? '';
        if (specifier.endsWith('.js')) {
          offenders.push(`${relative(repoRoot, file)}: ${specifier}`);
        }
      }
    }
    expect(offenders).toEqual([]);
  });

  /**
   * The root barrel is what the bug report actually hit: a web page importing `@agent-hangar/core`
   * pulls in every one of these re-exports. Asserting the exact specifiers here, rather than only
   * the generic scan above, keeps the regression test readable as a description of the fix.
   */
  it('re-exports every folder barrel from index.ts with a .ts specifier', () => {
    const indexContent = readFileSync(join(coreSrcDir, 'index.ts'), 'utf8');
    const folderBarrels = [
      './runner/index.ts',
      './model/index.ts',
      './agent-protocol/index.ts',
      './secrets/index.ts',
      './redaction/index.ts',
      './logging/index.ts',
      './scheduling/index.ts',
      './workspace/index.ts',
      './restore/index.ts',
      './persistence/index.ts',
      './queues/index.ts',
      './api/index.ts',
      './config/index.ts',
      './errors.ts',
    ];
    for (const barrel of folderBarrels) {
      expect(indexContent).toContain(`from '${barrel}'`);
    }
  });

  /**
   * The scan above is only as good as the pattern that feeds it: a specifier form the pattern
   * cannot see is a specifier the scan silently approves. A side-effect `import './x'` carries no
   * `from` keyword, so a pattern anchored on `from` alone reports a clean tree while the offending
   * import is still there. Each form is asserted individually so a future narrowing of the pattern
   * names the form it dropped instead of failing as one opaque case.
   */
  it.each([
    ['a named import clause', `import { thing } from './x.js';`],
    ['a namespace import clause', `import * as thing from './x.js';`],
    ['a type-only import clause', `import type { Thing } from './x.js';`],
    ['a re-export clause', `export * from './x.js';`],
    ['a dynamic import call', `await import('./x.js');`],
    ['a side-effect import with no binding', `import './x.js';`],
  ])('detects a relative specifier in %s', (_form, source) => {
    const found = [...source.matchAll(RELATIVE_SPECIFIER_PATTERN)].map((match) => match[1]);
    expect(found).toEqual(['./x.js']);
  });
});
