#!/usr/bin/env bash
# Derives the per-instance environment (ports, database, compose project, container prefix) from
# AH_INSTANCE / AH_PORT_BASE, falling back to CONDUCTOR_WORKSPACE_NAME / CONDUCTOR_PORT, then to
# default / 3000. Mirrors packages/core/src/config/instance.ts — a test keeps both in sync.
#
# Usage:
#   infra/scripts/env.sh            write .env.local if absent
#   infra/scripts/env.sh --force    overwrite .env.local
#   infra/scripts/env.sh --print    print `export KEY=value` lines (eval "$(infra/scripts/env.sh --print)")
#
# Runs on macOS bash 3.2: no associative arrays, no mapfile.
set -euo pipefail

ah_root_dir() {
  cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd
}

# Lowercase, anything outside [a-z0-9-] becomes "-", runs collapse, ends trimmed, max 30 chars.
ah_slugify() {
  local value
  value=$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9-]+/-/g; s/-+/-/g; s/^-//; s/-$//')
  value=${value:0:30}
  value=$(printf '%s' "$value" | sed -E 's/-$//')
  if [ -z "$value" ]; then
    value="default"
  fi
  printf '%s' "$value"
}

ah_first_non_empty() {
  local candidate
  for candidate in "$@"; do
    candidate=$(printf '%s' "$candidate" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')
    if [ -n "$candidate" ]; then
      printf '%s' "$candidate"
      return 0
    fi
  done
  return 0
}

# Exports every derived variable into the current shell.
ah_resolve_env() {
  local raw_instance raw_port
  raw_instance=$(ah_first_non_empty "${AH_INSTANCE:-}" "${CONDUCTOR_WORKSPACE_NAME:-}")
  raw_port=$(ah_first_non_empty "${AH_PORT_BASE:-}" "${CONDUCTOR_PORT:-}")
  if [ -z "$raw_instance" ]; then
    raw_instance="default"
  fi
  if [ -z "$raw_port" ]; then
    raw_port="3000"
  fi
  case "$raw_port" in
    ''|*[!0-9]*)
      echo "error: AH_PORT_BASE must be an integer between 1024 and 65000, got \"$raw_port\"" >&2
      return 1
      ;;
  esac
  if [ "$raw_port" -lt 1024 ] || [ "$raw_port" -gt 65000 ]; then
    echo "error: AH_PORT_BASE must be an integer between 1024 and 65000, got \"$raw_port\"" >&2
    return 1
  fi

  AH_INSTANCE=$(ah_slugify "$raw_instance")
  AH_PORT_BASE=$raw_port
  WEB_PORT=$((AH_PORT_BASE + 0))
  POSTGRES_PORT=$((AH_PORT_BASE + 1))
  REDIS_PORT=$((AH_PORT_BASE + 2))
  POSTGRES_DB="agent_hangar_$(printf '%s' "$AH_INSTANCE" | tr '-' '_')"
  # Local compose credentials (not a secret: loopback only, ciphertext-only contents).
  local db_scheme="postgresql" db_credentials="ah:ah"
  DATABASE_URL="${db_scheme}://${db_credentials}@127.0.0.1:${POSTGRES_PORT}/${POSTGRES_DB}"
  REDIS_URL="redis://127.0.0.1:${REDIS_PORT}"
  COMPOSE_PROJECT_NAME="agent-hangar-${AH_INSTANCE}"
  WORKSPACE_NAME_PREFIX="ah-ws-${AH_INSTANCE}-"
  WORKSPACE_IMAGE="${WORKSPACE_IMAGE:-agent-hangar/workspace:dev}"
  MASTER_KEY_PATH="${MASTER_KEY_PATH:-$HOME/.agent-hangar/master.key}"
  WORKSPACE_IDLE_TTL_MIN="${WORKSPACE_IDLE_TTL_MIN:-30}"
  WORKER_TURN_CONCURRENCY="${WORKER_TURN_CONCURRENCY:-2}"
  OPENAI_MODEL="${OPENAI_MODEL:-gpt-5.6-sol}"
  AGENT_MODEL_PROVIDER="${AGENT_MODEL_PROVIDER:-openai}"
  LOG_LEVEL="${LOG_LEVEL:-info}"
  export AH_INSTANCE AH_PORT_BASE WEB_PORT POSTGRES_PORT REDIS_PORT POSTGRES_DB DATABASE_URL \
    REDIS_URL COMPOSE_PROJECT_NAME WORKSPACE_NAME_PREFIX WORKSPACE_IMAGE MASTER_KEY_PATH \
    WORKSPACE_IDLE_TTL_MIN WORKER_TURN_CONCURRENCY OPENAI_MODEL AGENT_MODEL_PROVIDER LOG_LEVEL
}

AH_ENV_KEYS="AH_INSTANCE AH_PORT_BASE WEB_PORT POSTGRES_PORT REDIS_PORT POSTGRES_DB DATABASE_URL REDIS_URL COMPOSE_PROJECT_NAME WORKSPACE_NAME_PREFIX WORKSPACE_IMAGE MASTER_KEY_PATH WORKSPACE_IDLE_TTL_MIN WORKER_TURN_CONCURRENCY OPENAI_MODEL AGENT_MODEL_PROVIDER LOG_LEVEL"

# Prints KEY=value lines (optionally prefixed, e.g. "export ").
ah_print_env() {
  local prefix="${1:-}" key
  for key in $AH_ENV_KEYS; do
    printf '%s%s=%s\n' "$prefix" "$key" "${!key}"
  done
}

ah_write_env_file() {
  local target="$1"
  {
    echo "# Generated by infra/scripts/env.sh for instance \"$AH_INSTANCE\" — re-run with --force to regenerate."
    echo "# Secrets (GitHub PAT, OpenAI key) are NOT environment variables: enter them in Settings."
    ah_print_env ""
    echo "OPENAI_BASE_URL="
    echo "DOCKER_HOST="
    echo "NEXT_PUBLIC_API_MOCK=0"
  } > "$target"
}

ah_env_main() {
  local mode="write" root target
  case "${1:-}" in
    --print) mode="print" ;;
    --force) mode="force" ;;
    "") ;;
    *)
      echo "usage: env.sh [--print|--force]" >&2
      return 2
      ;;
  esac
  ah_resolve_env
  root=$(ah_root_dir)
  target="$root/.env.local"
  case "$mode" in
    print)
      ah_print_env "export "
      ;;
    force)
      ah_write_env_file "$target"
      echo "wrote $target (instance $AH_INSTANCE, ports $WEB_PORT/$POSTGRES_PORT/$REDIS_PORT)"
      ;;
    write)
      if [ -f "$target" ]; then
        echo "$target already exists (use --force to overwrite)"
      else
        ah_write_env_file "$target"
        echo "wrote $target (instance $AH_INSTANCE, ports $WEB_PORT/$POSTGRES_PORT/$REDIS_PORT)"
      fi
      ;;
  esac
}

# Only run when executed directly; sourcing just defines the functions.
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  ah_env_main "$@"
fi
